services:
  - type: web
    name: school-van-management-backend
    env: node
    rootDir: code/backend
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: JWT_EXPIRES_IN
        value: 8h
      - key: DATABASE_URL
        sync: false
      - key: FRONTEND_URL
        sync: false
      - key: JWT_SECRET
        sync: false
