# This theme is based on https://github.com/jekyll/minima
# Please refer above link to know the available configurations

title: "School Transport Vehicle Management System"
remote_theme: cepdnaclk/eYY-project-theme
description: "A real-time school van tracking and management system for parents, drivers, and administrators. Built with PERN stack and Socket.io."
markdown: kramdown

kramdown:
  parse_block_html: true
  syntax_highlighter_opts:
    block:
      line_numbers: false
